# Generated by Django 5.1.7 on 2025-03-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_rental_rented_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='user',
            new_name='user_name',
        ),
    ]
