# Generated by Django 5.1.7 on 2025-06-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rental_is_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
